name: GitHub - Activity - Readme

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update README with recent activity
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
        uses: actions/checkout@v2.3.4

    - name: Add activity to readme
      - uses: Readme-Workflows/recent-activity@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          CONFIG_FILE: './github/recent-activity-config.yml'
