name: Waka Readme

on:
  schedule:
    # Runs at the end of every day
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TOTAL_CODE_TIME: false
          SHOW_LINES_OF_CODE: false
          SHOW_PROFILE_VIEWS: false
          SHOW_DAYS_OF_WEEK: false
          SHOW_OS: true
          SHOW_PROJECTS: false
          SHOW_TIMEZONE: true
          SHOW_LANGUAGE_PER_REPO: false
          SHOW_LOC_CHART: false
